version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "nevermore/front"
    mem_limit: 512m
    cpus: 0.5
    container_name: nevermore_front
    restart: unless-stopped
    ports:
      - $PORT_FRONT:80
    
networks:
  default:
    external:
      name: nevermore_network